#!/bin/bash

user_desktop=`xdg-user-dir DESKTOP`
user_desktop_file="$user_desktop/tr.org.pardus.mycomputer.desktop"
root_desktop_file="/usr/share/applications/tr.org.pardus.mycomputer.desktop"

config_dir="$HOME/.config/pardus-mycomputer"
if ! [[ -d "$config_dir" ]]; then
  config_dir="$HOME/.config/pardus/pardus-mycomputer"
fi
config_file="$config_dir/desktop"

if ! [[ -f "$config_file" ]]; then
	if ! [[ -d "$config_dir" ]]; then
		mkdir -p "$config_dir"
	fi

	if ! [[ -f "$user_desktop_file" ]]; then
		if [[ -f "$root_desktop_file" ]]; then
			if [[ -d "$user_desktop" ]]; then
				cp "$root_desktop_file" "$user_desktop_file"
				chmod +x "$user_desktop_file"
				gio set "$user_desktop_file" "metadata::trusted" true
				gio set -t string "$user_desktop_file" metadata::xfce-exe-checksum "$(sha256sum "$user_desktop_file" | awk '{print $1}')"
			fi
		fi
	fi
	date "+%s" > "$config_file"
fi

exit 0
