#!/bin/bash

root_desktop_file="/usr/share/applications/tr.org.pardus.mycomputer.desktop"

homedir=$( getent passwd `logname` | cut -d: -f6 )

user_desktop="$homedir/Desktop"


if [[ -f "$homedir/.config/user-dirs.dirs" ]]; then
	user_desktop="$(HOME=$homedir eval echo -n $(cat "$homedir/.config/user-dirs.dirs" | grep XDG_DESKTOP_DIR | cut -f2 -d'='))"
elif [ -f /etc/xdg/user-dirs.defaults ]; then
	user_desktop="$homedir/$(cat /etc/xdg/user-dirs.defaults | grep DESKTOP | cut -f2 -d '=')"
fi

user_desktop_file="$user_desktop/tr.org.pardus.mycomputer.desktop"

if [[ -d "$user_desktop" ]] ; then
	if [[ -f "$root_desktop_file" ]]; then
		cp "$root_desktop_file" "$user_desktop"
		chown $(stat -c "%U:%G" $homedir) "$user_desktop_file"
		chmod +x "$user_desktop_file"
		gio set "$user_desktop_file" "metadata::trusted" true
	fi
fi


exit 0
